# ~/.config/matugen/templates/colors-kitty.conf
# Archivo de colores dinámicos generado por Matugen

foreground            #e1e2e8
background            #111418
cursor                #a1cafd
cursor_text_color     #003259
selection_foreground  #d2e4ff
selection_background  #1a4975
url_color             #d7bee4

# Colores de las pestañas (Tabs) por si las usás
active_tab_foreground   #003259
active_tab_background   #a1cafd
inactive_tab_foreground #c3c6cf
inactive_tab_background #43474e

# Los 16 colores de la terminal (ANSI)
# Normales
color0  #111418
color1  #ffb4ab
color2  #a1cafd
color3  #d7bee4
color4  #bbc7db
color5  #36618e
color6  #1a4975
color7  #e1e2e8

# Brillantes
color8  #43474e
color9  #ffb4ab
color10 #a1cafd
color11 #d7bee4
color12 #bbc7db
color13 #36618e
color14 #1a4975
color15 #e1e2e8
