# ~/.config/matugen/templates/colors-kitty.conf
# Archivo de colores dinámicos generado por Matugen

foreground            #e1e2e8
background            #101418
cursor                #9ecafc
cursor_text_color     #003256
selection_foreground  #d0e4ff
selection_background  #164974
url_color             #d5bee5

# Colores de las pestañas (Tabs) por si las usás
active_tab_foreground   #003256
active_tab_background   #9ecafc
inactive_tab_foreground #c2c7cf
inactive_tab_background #42474e

# Los 16 colores de la terminal (ANSI)
# Normales
color0  #101418
color1  #ffb4ab
color2  #9ecafc
color3  #d5bee5
color4  #bac8db
color5  #34618d
color6  #164974
color7  #e1e2e8

# Brillantes
color8  #42474e
color9  #ffb4ab
color10 #9ecafc
color11 #d5bee5
color12 #bac8db
color13 #34618d
color14 #164974
color15 #e1e2e8
