# ~/.config/matugen/templates/colors-kitty.conf
# Archivo de colores dinámicos generado por Matugen

foreground            #dde4e3
background            #0e1415
cursor                #80d4d6
cursor_text_color     #003738
selection_foreground  #9cf1f2
selection_background  #004f51
url_color             #b4c8e9

# Colores de las pestañas (Tabs) por si las usás
active_tab_foreground   #003738
active_tab_background   #80d4d6
inactive_tab_foreground #bec8c8
inactive_tab_background #3f4949

# Los 16 colores de la terminal (ANSI)
# Normales
color0  #0e1415
color1  #ffb4ab
color2  #80d4d6
color3  #b4c8e9
color4  #b0cccc
color5  #00696b
color6  #004f51
color7  #dde4e3

# Brillantes
color8  #3f4949
color9  #ffb4ab
color10 #80d4d6
color11 #b4c8e9
color12 #b0cccc
color13 #00696b
color14 #004f51
color15 #dde4e3
