# ~/.config/matugen/templates/colors-fuzzel.ini
[colors]
# Le agregamos 'cc' al final del background para mantener tu transparencia
background=0e1415cc
text=dde4e3ff
match=80d4d6ff
selection=3f4949ff
selection-text=bec8c8ff
border=80d4d6ff
