# ~/.config/matugen/templates/colors-fuzzel.ini
[colors]
# Le agregamos 'cc' al final del background para mantener tu transparencia
background=111418cc
text=e1e2e8ff
match=a1cafdff
selection=43474eff
selection-text=c3c6cfff
border=a1cafdff
