[main]
font=Noto Sans:size=11
icon-theme=Papirus-Dark
# Lupa de Nerd Fonts + un espacio para separar (Cópialo tal cual)
prompt="  " 
terminal=kitty # Cambia por la terminal que estés usando

# --- DIMENSIONES Y ESPACIOS COMPACTOS ---
lines=6              # Muestra solo 6 resultados a la vez (menos altura)
width=35             # Lo hace más estrecho (el defecto suele ser muy ancho)
horizontal-pad=20    # Espacio elegante a los lados
vertical-pad=15      # Espacio arriba y abajo
inner-pad=10         # Espacio entre el icono y el texto del programa

[colors]
# Tu paleta oscura y elegante
background=0a0a0acc
text=d4d4d4ff
match=ffffffff
selection=2b2b2bff
selection-text=ffffffff
border=333333ff

[border]
width=2              # Un borde sutil pero definido
radius=15            # Bordes redondeados para coincidir con Waybar
