# ~/.config/fuzzel/fuzzel.ini

# Importamos los colores generados por Matugen (Ponelo arriba de todo)
include=~/Documentos/Dotfiles/fuzzel/colors.ini

[main]
font=Noto Sans:size=11
icon-theme=Papirus-Dark
prompt="" 
terminal=kitty

# --- DIMENSIONES Y ESPACIOS COMPACTOS ---
lines=6              
width=35             
horizontal-pad=20    
vertical-pad=15      
inner-pad=10         

[border]
width=2              
radius=15
