# ~/.config/matugen/templates/colors-kitty.conf
# Archivo de colores dinámicos generado por Matugen

foreground            #dee3e5
background            #0e1416
cursor                #82d3e2
cursor_text_color     #00363e
selection_foreground  #9eefff
selection_background  #004e59
url_color             #bbc5eb

# Colores de las pestañas (Tabs) por si las usás
active_tab_foreground   #00363e
active_tab_background   #82d3e2
inactive_tab_foreground #bfc8ca
inactive_tab_background #3f484a

# Los 16 colores de la terminal (ANSI)
# Normales
color0  #0e1416
color1  #ffb4ab
color2  #82d3e2
color3  #bbc5eb
color4  #b1cbd1
color5  #006876
color6  #004e59
color7  #dee3e5

# Brillantes
color8  #3f484a
color9  #ffb4ab
color10 #82d3e2
color11 #bbc5eb
color12 #b1cbd1
color13 #006876
color14 #004e59
color15 #dee3e5
